#define UTS_VERSION "#5 Mon Oct 25 20:56:08 CEST 2004"
#define LINUX_COMPILE_TIME "20:56:08"
#define LINUX_COMPILE_BY "bellard"
#define LINUX_COMPILE_HOST "voyager.localdomain"
#define LINUX_COMPILE_DOMAIN "localdomain"
#define LINUX_COMPILER "TinyCC 0.9.21"
